name: Replace file in S3

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install and configure AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        aws configure set aws_access_key_id AKIA3QVN3JRMSTCOID5T
        aws configure set aws_secret_access_key CPYNG9zWnU3LwAjs8V2f1B2p3TbHZKdAUDchKQss
       

    - name: Replace file in S3
      run: |
        aws s3 cp ./ s3://memberbase.com --force
