trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install -y awscli
      aws configure set aws_access_key_id AKIA3QVN3JRMSTCOID5T
      aws configure set aws_secret_access_key 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
      aws configure set default.region us-east-1
      aws s3 cp ./ s3://memberbase.com  --recursive
  env:
    aws_access_key_id: AKIA3QVN3JRMSTCOID5T
    aws_secret_access_key: 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
    region: us-east-1